### ISSUE TITLE
Problem with showing up 

### ISSUE THREAD

**Issue by EILLOxX** [Ewan-Selkirk/Metadata-Customizer#3]
I'ts not showing up on any of my albums.
![image](https://github.com/Ewan-Selkirk/Metadata-Customizer/assets/128436412/00834ad0-421d-4644-95a9-0da42817a6c1)

**Comment by Ewan-Selkirk** [comment]
Sorry, I haven't used Spicetify in a while so it broke a lot.

Just pushed an update that should fix it. Let me know if it works for you!
